'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.EntityClient
Imports VRNS.DataModel.EntityModel

Partial Public Class VRNSEntities
    Inherits ObjectContext
    Public Const SettingsConnectionString As String = "name=VRNSEntities"
    Public Const ContainerName As String = "VRNSEntities"

#Region "Constructors"

    Public Sub New()
        MyBase.New(SettingsConnectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

#End Region
#Region "ObjectSet Properties"

    Public ReadOnly Property VRNS_Branch() As ObjectSet(Of VRNS_Branch)
        Get
            If _vRNS_Branch Is Nothing Then
                _vRNS_Branch = CreateObjectSet(Of VRNS_Branch)("VRNS_Branch")
            End If
            Return _vRNS_Branch
        End Get
    End Property
    Private _vRNS_Branch As ObjectSet(Of VRNS_Branch)

    Public ReadOnly Property VRNS_Branch_Operation() As ObjectSet(Of VRNS_Branch_Operation)
        Get
            If _vRNS_Branch_Operation Is Nothing Then
                _vRNS_Branch_Operation = CreateObjectSet(Of VRNS_Branch_Operation)("VRNS_Branch_Operation")
            End If
            Return _vRNS_Branch_Operation
        End Get
    End Property
    Private _vRNS_Branch_Operation As ObjectSet(Of VRNS_Branch_Operation)

    Public ReadOnly Property VRNS_Department() As ObjectSet(Of VRNS_Department)
        Get
            If _vRNS_Department Is Nothing Then
                _vRNS_Department = CreateObjectSet(Of VRNS_Department)("VRNS_Department")
            End If
            Return _vRNS_Department
        End Get
    End Property
    Private _vRNS_Department As ObjectSet(Of VRNS_Department)

    Public ReadOnly Property VRNS_Employee() As ObjectSet(Of VRNS_Employee)
        Get
            If _vRNS_Employee Is Nothing Then
                _vRNS_Employee = CreateObjectSet(Of VRNS_Employee)("VRNS_Employee")
            End If
            Return _vRNS_Employee
        End Get
    End Property
    Private _vRNS_Employee As ObjectSet(Of VRNS_Employee)

    Public ReadOnly Property VRNS_JOB() As ObjectSet(Of VRNS_JOB)
        Get
            If _vRNS_JOB Is Nothing Then
                _vRNS_JOB = CreateObjectSet(Of VRNS_JOB)("VRNS_JOB")
            End If
            Return _vRNS_JOB
        End Get
    End Property
    Private _vRNS_JOB As ObjectSet(Of VRNS_JOB)

    Public ReadOnly Property VRNS_MA_Team() As ObjectSet(Of VRNS_MA_Team)
        Get
            If _vRNS_MA_Team Is Nothing Then
                _vRNS_MA_Team = CreateObjectSet(Of VRNS_MA_Team)("VRNS_MA_Team")
            End If
            Return _vRNS_MA_Team
        End Get
    End Property
    Private _vRNS_MA_Team As ObjectSet(Of VRNS_MA_Team)

    Public ReadOnly Property VRNS_MA_Topic() As ObjectSet(Of VRNS_MA_Topic)
        Get
            If _vRNS_MA_Topic Is Nothing Then
                _vRNS_MA_Topic = CreateObjectSet(Of VRNS_MA_Topic)("VRNS_MA_Topic")
            End If
            Return _vRNS_MA_Topic
        End Get
    End Property
    Private _vRNS_MA_Topic As ObjectSet(Of VRNS_MA_Topic)

    Public ReadOnly Property VRNS_Maintainance_Detail() As ObjectSet(Of VRNS_Maintainance_Detail)
        Get
            If _vRNS_Maintainance_Detail Is Nothing Then
                _vRNS_Maintainance_Detail = CreateObjectSet(Of VRNS_Maintainance_Detail)("VRNS_Maintainance_Detail")
            End If
            Return _vRNS_Maintainance_Detail
        End Get
    End Property
    Private _vRNS_Maintainance_Detail As ObjectSet(Of VRNS_Maintainance_Detail)

    Public ReadOnly Property VRNS_Maintainance_Record() As ObjectSet(Of VRNS_Maintainance_Record)
        Get
            If _vRNS_Maintainance_Record Is Nothing Then
                _vRNS_Maintainance_Record = CreateObjectSet(Of VRNS_Maintainance_Record)("VRNS_Maintainance_Record")
            End If
            Return _vRNS_Maintainance_Record
        End Get
    End Property
    Private _vRNS_Maintainance_Record As ObjectSet(Of VRNS_Maintainance_Record)

    Public ReadOnly Property VRNS_Status() As ObjectSet(Of VRNS_Status)
        Get
            If _vRNS_Status Is Nothing Then
                _vRNS_Status = CreateObjectSet(Of VRNS_Status)("VRNS_Status")
            End If
            Return _vRNS_Status
        End Get
    End Property
    Private _vRNS_Status As ObjectSet(Of VRNS_Status)

    Public ReadOnly Property VRNS_Title() As ObjectSet(Of VRNS_Title)
        Get
            If _vRNS_Title Is Nothing Then
                _vRNS_Title = CreateObjectSet(Of VRNS_Title)("VRNS_Title")
            End If
            Return _vRNS_Title
        End Get
    End Property
    Private _vRNS_Title As ObjectSet(Of VRNS_Title)

    Public ReadOnly Property VRNS_ROLE() As ObjectSet(Of VRNS_ROLE)
        Get
            If _vRNS_ROLE Is Nothing Then
                _vRNS_ROLE = CreateObjectSet(Of VRNS_ROLE)("VRNS_ROLE")
            End If
            Return _vRNS_ROLE
        End Get
    End Property
    Private _vRNS_ROLE As ObjectSet(Of VRNS_ROLE)

    Public ReadOnly Property VRNS_Member() As ObjectSet(Of VRNS_Member)
        Get
            If _vRNS_Member Is Nothing Then
                _vRNS_Member = CreateObjectSet(Of VRNS_Member)("VRNS_Member")
            End If
            Return _vRNS_Member
        End Get
    End Property
    Private _vRNS_Member As ObjectSet(Of VRNS_Member)

    Public ReadOnly Property VRNS_Region() As ObjectSet(Of VRNS_Region)
        Get
            If _vRNS_Region Is Nothing Then
                _vRNS_Region = CreateObjectSet(Of VRNS_Region)("VRNS_Region")
            End If
            Return _vRNS_Region
        End Get
    End Property
    Private _vRNS_Region As ObjectSet(Of VRNS_Region)

    Public ReadOnly Property VRNS_Device_Registered() As ObjectSet(Of VRNS_Device_Registered)
        Get
            If _vRNS_Device_Registered Is Nothing Then
                _vRNS_Device_Registered = CreateObjectSet(Of VRNS_Device_Registered)("VRNS_Device_Registered")
            End If
            Return _vRNS_Device_Registered
        End Get
    End Property
    Private _vRNS_Device_Registered As ObjectSet(Of VRNS_Device_Registered)

#End Region
#Region "Function Imports"
    Public Function GETTOP10_DOWNTIME() As ObjectResult(Of GET_TOP10_DOWN_Result)
        Return MyBase.ExecuteFunction(Of GET_TOP10_DOWN_Result)("GETTOP10_DOWNTIME")
    End Function

#End Region
End Class
