'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Maintainance_Record
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Long
    
        Public Overridable Property Dev_Regis_ID As Long
            Get
                Return _dev_Regis_ID
            End Get
            Set(ByVal value As Long)
                Try
                    _settingFK = True
                    If Not Equals (_dev_Regis_ID, value) Then
                        If VRNS_Device_Registered IsNot Nothing AndAlso Not Equals(VRNS_Device_Registered.ID, value) Then
                            VRNS_Device_Registered = Nothing
                        End If
                        _dev_Regis_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _dev_Regis_ID As Long
    
        Public Overridable Property MA_TOPIC_CODE As String
            Get
                Return _mA_TOPIC_CODE
            End Get
            Set(ByVal value As String)
                Try
                    _settingFK = True
                    If Not Equals (_mA_TOPIC_CODE, value) Then
                        If VRNS_MA_Topic IsNot Nothing AndAlso Not Equals(VRNS_MA_Topic.CODE, value) Then
                            VRNS_MA_Topic = Nothing
                        End If
                        _mA_TOPIC_CODE = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _mA_TOPIC_CODE As String
    
        Public Overridable Property ROOT_CAUSE As String
    
        Public Overridable Property SOLUTION As String
    
        Public Overridable Property ASSIGNEE As Nullable(Of Long)
    
        Public Overridable Property JOB_ID As Nullable(Of Integer)
            Get
                Return _jOB_ID
            End Get
            Set(ByVal value As Nullable(Of Integer))
                Try
                    _settingFK = True
                    If Not Equals (_jOB_ID, value) Then
                        If VRNS_JOB IsNot Nothing AndAlso Not Equals(VRNS_JOB.ID, value) Then
                            VRNS_JOB = Nothing
                        End If
                        If VRNS_JOB1 IsNot Nothing AndAlso Not Equals(VRNS_JOB1.ID, value) Then
                            VRNS_JOB1 = Nothing
                        End If
                        _jOB_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _jOB_ID As Nullable(Of Integer)
    
        Public Overridable Property Status As Nullable(Of Boolean)
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property VRNS_Device_Registered As VRNS_Device_Registered
            Get
                Return _vRNS_Device_Registered
            End Get
            Set(ByVal value As VRNS_Device_Registered)
                If _vRNS_Device_Registered IsNot value Then
                    Dim previousValue As VRNS_Device_Registered = _vRNS_Device_Registered
                    _vRNS_Device_Registered = value
                    FixupVRNS_Device_Registered(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_Device_Registered As VRNS_Device_Registered
    
        Public Overridable Property VRNS_JOB As VRNS_JOB
            Get
                Return _vRNS_JOB
            End Get
            Set(ByVal value As VRNS_JOB)
                If _vRNS_JOB IsNot value Then
                    Dim previousValue As VRNS_JOB = _vRNS_JOB
                    _vRNS_JOB = value
                    FixupVRNS_JOB(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_JOB As VRNS_JOB
    
        Public Overridable Property VRNS_JOB1 As VRNS_JOB
            Get
                Return _vRNS_JOB1
            End Get
            Set(ByVal value As VRNS_JOB)
                If _vRNS_JOB1 IsNot value Then
                    Dim previousValue As VRNS_JOB = _vRNS_JOB1
                    _vRNS_JOB1 = value
                    FixupVRNS_JOB1(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_JOB1 As VRNS_JOB
    
        Public Overridable Property VRNS_MA_Topic As VRNS_MA_Topic
            Get
                Return _vRNS_MA_Topic
            End Get
            Set(ByVal value As VRNS_MA_Topic)
                If _vRNS_MA_Topic IsNot value Then
                    Dim previousValue As VRNS_MA_Topic = _vRNS_MA_Topic
                    _vRNS_MA_Topic = value
                    FixupVRNS_MA_Topic(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_MA_Topic As VRNS_MA_Topic
        Public Overridable Property VRNS_Maintainance_Detail As ICollection(Of VRNS_Maintainance_Detail)
            Get
                If _vRNS_Maintainance_Detail Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Maintainance_Detail)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    _vRNS_Maintainance_Detail = newCollection
                End If
                Return _vRNS_Maintainance_Detail
            End Get
            Set(ByVal value As ICollection(Of VRNS_Maintainance_Detail))
                If _vRNS_Maintainance_Detail IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Maintainance_Detail) = TryCast(_vRNS_Maintainance_Detail, FixupCollection(Of VRNS_Maintainance_Detail))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    End If
                    _vRNS_Maintainance_Detail = value
                    Dim newValue As FixupCollection(Of VRNS_Maintainance_Detail) = TryCast(value, FixupCollection(Of VRNS_Maintainance_Detail))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Maintainance_Detail As ICollection(Of VRNS_Maintainance_Detail)

        #End Region
        #Region "Association Fixup"
        Private _settingFK As Boolean = False
    
        Private Sub FixupVRNS_Device_Registered(ByVal previousValue As VRNS_Device_Registered)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Record.Contains(Me) Then
                previousValue.VRNS_Maintainance_Record.Remove(Me)
            End If
            If VRNS_Device_Registered IsNot Nothing Then
                If Not VRNS_Device_Registered.VRNS_Maintainance_Record.Contains(Me) Then
                    VRNS_Device_Registered.VRNS_Maintainance_Record.Add(Me)
                End If
                If Not Equals(Dev_Regis_ID, VRNS_Device_Registered.ID) Then
                    Dev_Regis_ID = VRNS_Device_Registered.ID
                End If
            End If
        End Sub
    
        Private Sub FixupVRNS_JOB(ByVal previousValue As VRNS_JOB)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Record.Contains(Me) Then
                previousValue.VRNS_Maintainance_Record.Remove(Me)
            End If
            If VRNS_JOB IsNot Nothing Then
                If Not VRNS_JOB.VRNS_Maintainance_Record.Contains(Me) Then
                    VRNS_JOB.VRNS_Maintainance_Record.Add(Me)
                End If
                If Not Equals(JOB_ID, VRNS_JOB.ID) Then
                    JOB_ID = VRNS_JOB.ID
                End If
            ElseIf Not _settingFK Then
                JOB_ID = Nothing
            End If
        End Sub
    
        Private Sub FixupVRNS_JOB1(ByVal previousValue As VRNS_JOB)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Record1.Contains(Me) Then
                previousValue.VRNS_Maintainance_Record1.Remove(Me)
            End If
            If VRNS_JOB1 IsNot Nothing Then
                If Not VRNS_JOB1.VRNS_Maintainance_Record1.Contains(Me) Then
                    VRNS_JOB1.VRNS_Maintainance_Record1.Add(Me)
                End If
                If Not Equals(JOB_ID, VRNS_JOB1.ID) Then
                    JOB_ID = VRNS_JOB1.ID
                End If
            ElseIf Not _settingFK Then
                JOB_ID = Nothing
            End If
        End Sub
    
        Private Sub FixupVRNS_MA_Topic(ByVal previousValue As VRNS_MA_Topic)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Record.Contains(Me) Then
                previousValue.VRNS_Maintainance_Record.Remove(Me)
            End If
            If VRNS_MA_Topic IsNot Nothing Then
                If Not VRNS_MA_Topic.VRNS_Maintainance_Record.Contains(Me) Then
                    VRNS_MA_Topic.VRNS_Maintainance_Record.Add(Me)
                End If
                If Not Equals(MA_TOPIC_CODE, VRNS_MA_Topic.CODE) Then
                    MA_TOPIC_CODE = VRNS_MA_Topic.CODE
                End If
            ElseIf Not _settingFK Then
                MA_TOPIC_CODE = Nothing
            End If
        End Sub
        Private Sub FixupVRNS_Maintainance_Detail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Maintainance_Detail In e.NewItems
                    item.VRNS_Maintainance_Record = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Maintainance_Detail In e.OldItems
                    If item.VRNS_Maintainance_Record Is Me Then
                        item.VRNS_Maintainance_Record = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
