'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Maintainance_Detail
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Long
    
        Public Overridable Property Maintainance_Record_ID As Long
            Get
                Return _maintainance_Record_ID
            End Get
            Set(ByVal value As Long)
                Try
                    _settingFK = True
                    If Not Equals (_maintainance_Record_ID, value) Then
                        If VRNS_Maintainance_Record IsNot Nothing AndAlso Not Equals(VRNS_Maintainance_Record.ID, value) Then
                            Dim previousValue As VRNS_Maintainance_Record = _vRNS_Maintainance_Record
                            _vRNS_Maintainance_Record = Nothing
                            FixupVRNS_Maintainance_Record(previousValue, skipKeys:=True)
                        End If
                        _maintainance_Record_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _maintainance_Record_ID As Long
    
        Public Overridable Property Dev_Regis_ID As Nullable(Of Long)
            Get
                Return _dev_Regis_ID
            End Get
            Set(ByVal value As Nullable(Of Long))
                Try
                    _settingFK = True
                    If Not Equals (_dev_Regis_ID, value) Then
                        If VRNS_Maintainance_Record IsNot Nothing AndAlso Not Equals(VRNS_Maintainance_Record.Dev_Regis_ID, value) Then
                            Dim previousValue As VRNS_Maintainance_Record = _vRNS_Maintainance_Record
                            _vRNS_Maintainance_Record = Nothing
                            FixupVRNS_Maintainance_Record(previousValue, skipKeys:=True)
                        End If
                        _dev_Regis_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _dev_Regis_ID As Nullable(Of Long)
    
        Public Overridable Property EMP_MA As Nullable(Of Long)
            Get
                Return _eMP_MA
            End Get
            Set(ByVal value As Nullable(Of Long))
                Try
                    _settingFK = True
                    If Not Equals (_eMP_MA, value) Then
                        If VRNS_MA_Team IsNot Nothing AndAlso Not Equals(VRNS_MA_Team.ID, value) Then
                            VRNS_MA_Team = Nothing
                        End If
                        _eMP_MA = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _eMP_MA As Nullable(Of Long)
    
        Public Overridable Property EMP_Contact_ID As String
            Get
                Return _eMP_Contact_ID
            End Get
            Set(ByVal value As String)
                Try
                    _settingFK = True
                    If Not Equals (_eMP_Contact_ID, value) Then
                        If VRNS_Employee IsNot Nothing AndAlso Not Equals(VRNS_Employee.ID, value) Then
                            VRNS_Employee = Nothing
                        End If
                        _eMP_Contact_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _eMP_Contact_ID As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property VRNS_Employee As VRNS_Employee
            Get
                Return _vRNS_Employee
            End Get
            Set(ByVal value As VRNS_Employee)
                If _vRNS_Employee IsNot value Then
                    Dim previousValue As VRNS_Employee = _vRNS_Employee
                    _vRNS_Employee = value
                    FixupVRNS_Employee(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_Employee As VRNS_Employee
    
        Public Overridable Property VRNS_MA_Team As VRNS_MA_Team
            Get
                Return _vRNS_MA_Team
            End Get
            Set(ByVal value As VRNS_MA_Team)
                If _vRNS_MA_Team IsNot value Then
                    Dim previousValue As VRNS_MA_Team = _vRNS_MA_Team
                    _vRNS_MA_Team = value
                    FixupVRNS_MA_Team(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_MA_Team As VRNS_MA_Team
    
        Public Overridable Property VRNS_Maintainance_Record As VRNS_Maintainance_Record
            Get
                Return _vRNS_Maintainance_Record
            End Get
            Set(ByVal value As VRNS_Maintainance_Record)
                If _vRNS_Maintainance_Record IsNot value Then
                    Dim previousValue As VRNS_Maintainance_Record = _vRNS_Maintainance_Record
                    _vRNS_Maintainance_Record = value
                    FixupVRNS_Maintainance_Record(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_Maintainance_Record As VRNS_Maintainance_Record

        #End Region
        #Region "Association Fixup"
        Private _settingFK As Boolean = False
    
        Private Sub FixupVRNS_Employee(ByVal previousValue As VRNS_Employee)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Detail.Contains(Me) Then
                previousValue.VRNS_Maintainance_Detail.Remove(Me)
            End If
            If VRNS_Employee IsNot Nothing Then
                If Not VRNS_Employee.VRNS_Maintainance_Detail.Contains(Me) Then
                    VRNS_Employee.VRNS_Maintainance_Detail.Add(Me)
                End If
                If Not Equals(EMP_Contact_ID, VRNS_Employee.ID) Then
                    EMP_Contact_ID = VRNS_Employee.ID
                End If
            ElseIf Not _settingFK Then
                EMP_Contact_ID = Nothing
            End If
        End Sub
    
        Private Sub FixupVRNS_MA_Team(ByVal previousValue As VRNS_MA_Team)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Detail.Contains(Me) Then
                previousValue.VRNS_Maintainance_Detail.Remove(Me)
            End If
            If VRNS_MA_Team IsNot Nothing Then
                If Not VRNS_MA_Team.VRNS_Maintainance_Detail.Contains(Me) Then
                    VRNS_MA_Team.VRNS_Maintainance_Detail.Add(Me)
                End If
                If Not Equals(EMP_MA, VRNS_MA_Team.ID) Then
                    EMP_MA = VRNS_MA_Team.ID
                End If
            ElseIf Not _settingFK Then
                EMP_MA = Nothing
            End If
        End Sub
    
        Private Sub FixupVRNS_Maintainance_Record(ByVal previousValue As VRNS_Maintainance_Record, Optional ByVal skipKeys As Boolean = False)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Maintainance_Detail.Contains(Me) Then
                previousValue.VRNS_Maintainance_Detail.Remove(Me)
            End If
            If VRNS_Maintainance_Record IsNot Nothing Then
                If Not VRNS_Maintainance_Record.VRNS_Maintainance_Detail.Contains(Me) Then
                    VRNS_Maintainance_Record.VRNS_Maintainance_Detail.Add(Me)
                End If
                If Not Equals(Maintainance_Record_ID, VRNS_Maintainance_Record.ID) Then
                    Maintainance_Record_ID = VRNS_Maintainance_Record.ID
                End If
                If Not Equals(Dev_Regis_ID, VRNS_Maintainance_Record.Dev_Regis_ID) Then
                    Dev_Regis_ID = VRNS_Maintainance_Record.Dev_Regis_ID
                End If
            ElseIf Not skipKeys AndAlso Not _settingFK Then
                Dev_Regis_ID = Nothing
            End If
        End Sub

        #End Region
    End Class
End Namespace
