'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_MA_Team
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Long
    
        Public Overridable Property EMP_ID As String
            Get
                Return _eMP_ID
            End Get
            Set(ByVal value As String)
                Try
                    _settingFK = True
                    If Not Equals (_eMP_ID, value) Then
                        If VRNS_Employee IsNot Nothing AndAlso Not Equals(VRNS_Employee.ID, value) Then
                            VRNS_Employee = Nothing
                        End If
                        _eMP_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _eMP_ID As String
    
        Public Overridable Property SKILL As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property VRNS_Employee As VRNS_Employee
            Get
                Return _vRNS_Employee
            End Get
            Set(ByVal value As VRNS_Employee)
                If _vRNS_Employee IsNot value Then
                    Dim previousValue As VRNS_Employee = _vRNS_Employee
                    _vRNS_Employee = value
                    FixupVRNS_Employee(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_Employee As VRNS_Employee
        Public Overridable Property VRNS_Maintainance_Detail As ICollection(Of VRNS_Maintainance_Detail)
            Get
                If _vRNS_Maintainance_Detail Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Maintainance_Detail)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    _vRNS_Maintainance_Detail = newCollection
                End If
                Return _vRNS_Maintainance_Detail
            End Get
            Set(ByVal value As ICollection(Of VRNS_Maintainance_Detail))
                If _vRNS_Maintainance_Detail IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Maintainance_Detail) = TryCast(_vRNS_Maintainance_Detail, FixupCollection(Of VRNS_Maintainance_Detail))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    End If
                    _vRNS_Maintainance_Detail = value
                    Dim newValue As FixupCollection(Of VRNS_Maintainance_Detail) = TryCast(value, FixupCollection(Of VRNS_Maintainance_Detail))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Maintainance_Detail
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Maintainance_Detail As ICollection(Of VRNS_Maintainance_Detail)

        #End Region
        #Region "Association Fixup"
        Private _settingFK As Boolean = False
    
        Private Sub FixupVRNS_Employee(ByVal previousValue As VRNS_Employee)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_MA_Team.Contains(Me) Then
                previousValue.VRNS_MA_Team.Remove(Me)
            End If
            If VRNS_Employee IsNot Nothing Then
                If Not VRNS_Employee.VRNS_MA_Team.Contains(Me) Then
                    VRNS_Employee.VRNS_MA_Team.Add(Me)
                End If
                If Not Equals(EMP_ID, VRNS_Employee.ID) Then
                    EMP_ID = VRNS_Employee.ID
                End If
            ElseIf Not _settingFK Then
                EMP_ID = Nothing
            End If
        End Sub
        Private Sub FixupVRNS_Maintainance_Detail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Maintainance_Detail In e.NewItems
                    item.VRNS_MA_Team = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Maintainance_Detail In e.OldItems
                    If item.VRNS_MA_Team Is Me Then
                        item.VRNS_MA_Team = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
