'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_ROLE
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Integer
    
        Public Overridable Property CODE As String
    
        Public Overridable Property DESCRIPTION As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
        Public Overridable Property VRNS_Member As ICollection(Of VRNS_Member)
            Get
                If _vRNS_Member Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Member)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Member
                    _vRNS_Member = newCollection
                End If
                Return _vRNS_Member
            End Get
            Set(ByVal value As ICollection(Of VRNS_Member))
                If _vRNS_Member IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Member) = TryCast(_vRNS_Member, FixupCollection(Of VRNS_Member))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Member
                    End If
                    _vRNS_Member = value
                    Dim newValue As FixupCollection(Of VRNS_Member) = TryCast(value, FixupCollection(Of VRNS_Member))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Member
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Member As ICollection(Of VRNS_Member)

        #End Region
        #Region "Association Fixup"
        Private Sub FixupVRNS_Member(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Member In e.NewItems
                    item.VRNS_ROLE = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Member In e.OldItems
                    If item.VRNS_ROLE Is Me Then
                        item.VRNS_ROLE = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
