'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Branch_Operation
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Integer
    
        Public Overridable Property PATTERN_ID As Nullable(Of Integer)
    
        Public Overridable Property DAY As String
    
        Public Overridable Property START_TIME As String
    
        Public Overridable Property END_TIME As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
        Public Overridable Property VRNS_Branch As ICollection(Of VRNS_Branch)
            Get
                If _vRNS_Branch Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Branch)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Branch
                    _vRNS_Branch = newCollection
                End If
                Return _vRNS_Branch
            End Get
            Set(ByVal value As ICollection(Of VRNS_Branch))
                If _vRNS_Branch IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Branch) = TryCast(_vRNS_Branch, FixupCollection(Of VRNS_Branch))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Branch
                    End If
                    _vRNS_Branch = value
                    Dim newValue As FixupCollection(Of VRNS_Branch) = TryCast(value, FixupCollection(Of VRNS_Branch))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Branch
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Branch As ICollection(Of VRNS_Branch)

        #End Region
        #Region "Association Fixup"
        Private Sub FixupVRNS_Branch(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Branch In e.NewItems
                    item.VRNS_Branch_Operation = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Branch In e.OldItems
                    If item.VRNS_Branch_Operation Is Me Then
                        item.VRNS_Branch_Operation = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
