'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Department
        #Region "Primitive Properties"
    
        Public Overridable Property CODE As Integer
    
        Public Overridable Property NAME As String
    
        Public Overridable Property DESCRIPTION As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
        Public Overridable Property VRNS_Employee As ICollection(Of VRNS_Employee)
            Get
                If _vRNS_Employee Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Employee)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Employee
                    _vRNS_Employee = newCollection
                End If
                Return _vRNS_Employee
            End Get
            Set(ByVal value As ICollection(Of VRNS_Employee))
                If _vRNS_Employee IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Employee) = TryCast(_vRNS_Employee, FixupCollection(Of VRNS_Employee))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Employee
                    End If
                    _vRNS_Employee = value
                    Dim newValue As FixupCollection(Of VRNS_Employee) = TryCast(value, FixupCollection(Of VRNS_Employee))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Employee
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Employee As ICollection(Of VRNS_Employee)

        #End Region
        #Region "Association Fixup"
        Private Sub FixupVRNS_Employee(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Employee In e.NewItems
                    item.VRNS_Department = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Employee In e.OldItems
                    If item.VRNS_Department Is Me Then
                        item.VRNS_Department = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
