'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Member
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Integer
    
        Public Overridable Property USER_LOGIN As String
    
        Public Overridable Property USER_NAME As String
    
        Public Overridable Property USER_PASSWORD As String
    
        Public Overridable Property ROLE As String
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
    End Class
End Namespace
