'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Branch
        #Region "Primitive Properties"
    
        Public Overridable Property CODE As String
    
        Public Overridable Property NAME As String
    
        Public Overridable Property TELEPHONE As String
    
        Public Overridable Property MOBILE As String
    
        Public Overridable Property OPERATION_ID As Nullable(Of Integer)
            Get
                Return _oPERATION_ID
            End Get
            Set(ByVal value As Nullable(Of Integer))
                Try
                    _settingFK = True
                    If Not Equals (_oPERATION_ID, value) Then
                        If VRNS_Branch_Operation IsNot Nothing AndAlso Not Equals(VRNS_Branch_Operation.ID, value) Then
                            VRNS_Branch_Operation = Nothing
                        End If
                        _oPERATION_ID = value
                    End If
                Finally
                    _settingFK = False
                End Try
            End Set
        End Property
        Private _oPERATION_ID As Nullable(Of Integer)
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property VRNS_Branch_Operation As VRNS_Branch_Operation
            Get
                Return _vRNS_Branch_Operation
            End Get
            Set(ByVal value As VRNS_Branch_Operation)
                If _vRNS_Branch_Operation IsNot value Then
                    Dim previousValue As VRNS_Branch_Operation = _vRNS_Branch_Operation
                    _vRNS_Branch_Operation = value
                    FixupVRNS_Branch_Operation(previousValue)
                End If
            End Set
        End Property
        Private _vRNS_Branch_Operation As VRNS_Branch_Operation
        Public Overridable Property VRNS_Employee As ICollection(Of VRNS_Employee)
            Get
                If _vRNS_Employee Is Nothing Then
                    Dim newCollection As New FixupCollection(Of VRNS_Employee)
                    AddHandler newCollection.CollectionChanged, AddressOf FixupVRNS_Employee
                    _vRNS_Employee = newCollection
                End If
                Return _vRNS_Employee
            End Get
            Set(ByVal value As ICollection(Of VRNS_Employee))
                If _vRNS_Employee IsNot value Then
                    Dim previousValue As FixupCollection(Of VRNS_Employee) = TryCast(_vRNS_Employee, FixupCollection(Of VRNS_Employee))
                    If previousValue IsNot Nothing Then
                        RemoveHandler previousValue.CollectionChanged, AddressOf FixupVRNS_Employee
                    End If
                    _vRNS_Employee = value
                    Dim newValue As FixupCollection(Of VRNS_Employee) = TryCast(value, FixupCollection(Of VRNS_Employee))
                    If newValue IsNot Nothing Then
                        AddHandler newValue.CollectionChanged, AddressOf FixupVRNS_Employee
                    End If
                End If
            End Set
        End Property
        Private _vRNS_Employee As ICollection(Of VRNS_Employee)

        #End Region
        #Region "Association Fixup"
        Private _settingFK As Boolean = False
    
        Private Sub FixupVRNS_Branch_Operation(ByVal previousValue As VRNS_Branch_Operation)
            If previousValue IsNot Nothing AndAlso previousValue.VRNS_Branch.Contains(Me) Then
                previousValue.VRNS_Branch.Remove(Me)
            End If
            If VRNS_Branch_Operation IsNot Nothing Then
                If Not VRNS_Branch_Operation.VRNS_Branch.Contains(Me) Then
                    VRNS_Branch_Operation.VRNS_Branch.Add(Me)
                End If
                If Not Equals(OPERATION_ID, VRNS_Branch_Operation.ID) Then
                    OPERATION_ID = VRNS_Branch_Operation.ID
                End If
            ElseIf Not _settingFK Then
                OPERATION_ID = Nothing
            End If
        End Sub
        Private Sub FixupVRNS_Employee(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            If e.NewItems IsNot Nothing Then
                For Each item As VRNS_Employee In e.NewItems
                    item.VRNS_Branch = Me
                Next
            End If
            If e.OldItems IsNot Nothing Then
                For Each item As VRNS_Employee In e.OldItems
                    If item.VRNS_Branch Is Me Then
                        item.VRNS_Branch = Nothing
                    End If
                Next
            End If
        End Sub

        #End Region
    End Class
End Namespace
