'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Namespace EntityModel
    <Serializable()> _
    Partial Public Class VRNS_Device_Registered_backup
        #Region "Primitive Properties"
    
        Public Overridable Property ID As Long
    
        Public Overridable Property BRANCH_CODE As String
    
        Public Overridable Property WAN_IP As String
    
        Public Overridable Property LAN_IP As String
    
        Public Overridable Property LAN_SUBNET As String
    
        Public Overridable Property ISP As String
    
        Public Overridable Property Cur_Status_CODE As Nullable(Of Integer)
    
        Public Overridable Property Cur_Status_UPD As Nullable(Of Date)
    
        Public Overridable Property Cur_Status_F As Nullable(Of Boolean)
    
        Public Overridable Property Prev_Status_CODE As Nullable(Of Integer)
    
        Public Overridable Property Prev_Status_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD As Nullable(Of Date)
    
        Public Overridable Property LAST_UPD_LOGIN As String
    
        Public Overridable Property LAST_UPD_DISPLAY_NM As String

        #End Region
    End Class
End Namespace
